import scheduledPosts from '@/lib/data/seo-scheduled-posts.json';

export const BASE_URL = 'https://www.assetliftlending.com';

export const PRIORITY_STATE_SLUGS = new Set(['new-york', 'new-jersey', 'connecticut']);

export const PRIORITY_CITY_PATHS = new Set([
  '/lending/new-jersey/camden-county',
  '/lending/new-jersey/ocean-county',
  '/lending/new-jersey/lakewood',
  '/lending/new-jersey/toms-river',
  '/lending/new-jersey/brick',
  '/lending/new-jersey/jackson',
  '/lending/new-jersey/howell',
  '/lending/new-jersey/freehold',
  '/lending/new-jersey/middletown',
  '/lending/new-jersey/red-bank',
  '/lending/new-jersey/long-branch',
  '/lending/new-jersey/edison',
  '/lending/new-jersey/woodbridge',
  '/lending/new-jersey/new-brunswick',
  '/lending/new-jersey/old-bridge',
  '/lending/new-jersey/camden',
  '/lending/new-jersey/cherry-hill',
  '/lending/new-jersey/pennsauken',
  '/lending/new-jersey/jersey-city',
  '/lending/new-jersey/newark',
  '/lending/new-jersey/ocean-county',
  '/lending/new-york/nassau-county',
  '/lending/new-york/yonkers',
  '/lending/new-york/brooklyn',
  '/lending/new-york/buffalo',
  '/lending/new-york/rochester',
  '/lending/new-york/syracuse',
  '/lending/new-jersey/paterson',
  '/lending/new-jersey/elizabeth',
  '/lending/new-jersey/bergen-county',
  '/lending/new-jersey/hudson-county',
  '/lending/new-jersey/essex-county',
  '/lending/new-jersey/union-county',
  '/lending/new-jersey/middlesex-county',
  '/lending/new-jersey/monmouth-county',
  '/lending/new-jersey/passaic-county',
  '/lending/new-jersey/morris-county',
  '/lending/new-jersey/trenton',
  '/lending/new-jersey/atlantic-city',
  '/lending/new-jersey/east-orange',
  '/lending/new-jersey/plainfield',
  '/lending/new-york/queens',
  '/lending/new-york/bronx',
  '/lending/new-york/manhattan',
  '/lending/new-york/staten-island',
  '/lending/new-york/suffolk-county',
  '/lending/new-york/westchester-county',
  '/lending/new-york/albany',
  '/lending/new-york/white-plains',
  '/lending/new-jersey/gloucester-county',
  '/lending/new-jersey/burlington-county',
  '/lending/new-jersey/mercer-county',
  '/lending/new-jersey/somerset-county',
  '/lending/new-jersey/atlantic-county',
  '/lending/new-jersey/cumberland-county',
  '/lending/new-jersey/salem-county',
  '/lending/new-jersey/sussex-county',
  '/lending/new-jersey/warren-county',
  '/lending/new-jersey/hunterdon-county',
  '/lending/new-jersey/cape-may-county',
  '/lending/new-jersey/gloucester-township',
  '/lending/new-jersey/voorhees',
  '/lending/new-jersey/winslow-township',
  '/lending/new-jersey/deptford',
  '/lending/new-jersey/mount-laurel',
  '/lending/new-jersey/evesham',
  '/lending/new-jersey/washington-township-gloucester',
  '/lending/new-jersey/hamilton-township-mercer',
  '/lending/new-jersey/egg-harbor-township',
  '/lending/new-jersey/vineland',
  '/lending/new-jersey/bayonne',
  '/lending/new-jersey/hoboken',
  '/lending/new-jersey/fort-lee',
  '/lending/new-jersey/clifton',
  '/lending/new-jersey/wayne',
  '/lending/new-jersey/parsippany',
  '/lending/new-jersey/hackensack',
  '/lending/new-jersey/teaneck',
  '/lending/new-jersey/irvington',
  '/lending/new-jersey/montclair',
  '/lending/new-jersey/marlboro',
  '/lending/new-jersey/manalapan',
  '/lending/new-jersey/wall-township',
  '/lending/new-jersey/stafford-township',
  '/lending/new-jersey/manchester',
  '/lending/new-jersey/berkeley-township',
  '/lending/new-jersey/piscataway',
  '/lending/new-jersey/perth-amboy',
  '/lending/new-jersey/sayreville',
  '/lending/new-jersey/south-brunswick',
  '/lending/new-jersey/willingboro',
  '/lending/new-jersey/linden',
  '/lending/new-jersey/kearny',
  '/lending/new-jersey/west-new-york',
  '/lending/new-jersey/north-bergen',
  '/lending/new-jersey/union-city',
  '/lending/new-york/hempstead',
  '/lending/new-york/freeport',
  '/lending/new-york/levittown',
  '/lending/new-york/hicksville',
  '/lending/new-york/valley-stream',
  '/lending/new-york/long-beach',
  '/lending/new-york/glen-cove',
  '/lending/new-york/garden-city',
  '/lending/new-york/huntington',
  '/lending/new-york/babylon',
  '/lending/new-york/islip',
  '/lending/new-york/brookhaven',
  '/lending/new-york/smithtown',
  '/lending/new-york/brentwood',
  '/lending/new-york/riverhead',
  '/lending/new-york/patchogue',
  '/lending/new-york/new-rochelle',
  '/lending/new-york/mount-vernon',
  '/lending/new-york/peekskill',
  '/lending/new-york/ossining',
  '/lending/new-york/port-chester',
  '/lending/new-york/rockland-county',
  '/lending/new-york/spring-valley',
  '/lending/new-york/newburgh',
  '/lending/new-york/middletown',
  '/lending/new-york/poughkeepsie',
  '/lending/new-york/beacon',
  '/lending/new-york/kingston',
  '/lending/new-york/saratoga-springs',
  '/lending/new-york/schenectady',
  '/lending/new-york/troy',
  '/lending/new-york/utica',
  '/lending/new-york/binghamton',
  '/lending/new-york/niagara-falls',
  '/lending/new-york/ithaca',
]);

export const INDEXABLE_STATIC_PATHS = new Set([
  '/',
  '/apply',
  '/about',
  '/contact',
  '/how-it-works',
  '/how-funding-works',
  '/state-disclosures',
  '/privacy',
  '/terms',
  '/licensing',
  '/faq',
  '/markets',
  '/loans',
  '/loans/fix-and-flip',
  '/loans/dscr-rental',
  '/loans/ground-up-construction',
  '/loans/bridge',
  '/tools',
  '/tools/fix-and-flip-calculator',
  '/tools/dscr-calculator',
  '/resources/fix-and-flip-deal-checklist',
  '/resources/fix-and-flip-borrower-package',
]);

export const NOINDEX_STATIC_PATHS = new Set([
  '/ai-context',
  '/answers',
  '/blog',
  '/brokers',
  '/compare',
  '/loans/commercial-lending',
  '/seo-status',
  '/team',
  '/tools/term-sheet-pricer',
]);

// Posts a person reviewed, approved and published from the AssetLift CRM SEO Hub
// (source: 'crm', indexable: true). Automated pipeline posts stay out unless listed below.
const CRM_REVIEWED_BLOG_SLUGS = (scheduledPosts as Array<{ slug: string; source?: string; indexable?: boolean }>)
  .filter((post) => post.source === 'crm' && post.indexable === true)
  .map((post) => post.slug);

export const INDEXABLE_BLOG_SLUGS = new Set([
  ...CRM_REVIEWED_BLOG_SLUGS,
  'dscr-loans-explained',
  'how-to-qualify-for-dscr-loan',
  'dscr-loan-for-rental-property',
  'how-does-a-dscr-loan-work',
  'brrrr-refinance-into-dscr-loan',
  'dscr-loan-for-short-term-rental',
  'dscr-loan-llc-vs-personal-name',
  'brrrr-method-complete-guide-2026',
  'hard-money-lender-prepayment-penalty',
  'fix-and-flip-loan-rehab-draw-process',
  'dscr-loan-rental-income-calculation',
  'bridge-loan-vs-hard-money-loan',
  'ground-up-construction-loan-requirements',
  'fix-and-flip-loan-requirements',
  'hard-money-loan-rates-2026',
  'how-to-calculate-after-repair-value',
]);

export const INDEXABLE_COMPARISON_SLUGS = new Set([
  'hard-money-loans-vs-conventional-mortgages',
  'fix-and-flip-vs-brrrr-strategy',
  'dscr-loans-vs-conventional-rental-loans',
  'bridge-loans-vs-hard-money-loans',
]);

export const INDEXABLE_ANSWER_SLUGS = new Set([
  'best-hard-money-lender-fix-and-flip',
  'best-dscr-lender-no-income-verification',
  'fix-and-flip-loans-100-percent-rehab-funding',
  'asset-based-loan-companies-real-estate-investors',
]);

export function isPriorityStatePath(path: string) {
  const stateSlug = path.replace('/lending/', '').split('/')[0];
  return PRIORITY_STATE_SLUGS.has(stateSlug);
}

export function shouldIndexState(stateSlug: string) {
  return PRIORITY_STATE_SLUGS.has(stateSlug);
}

export function shouldIndexCity(stateSlug: string, citySlug: string) {
  return PRIORITY_CITY_PATHS.has(`/lending/${stateSlug}/${citySlug}`);
}
